### ISSUE TITLE
Where can i find dataset?

### ISSUE THREAD

**Issue by imliupu** [Leohh123/FS-Net-PyTorch#1]

**Comment by Leohh123** [comment]
I'm sorry that the dataset I used cannot be made public due to privacy issues. By the way, there are still bugs in my codes, please refer to the paper Liu, Chang, et al. "Fs-net: A flow sequence network for encrypted traffic classification." IEEE INFOCOM 2019-IEEE Conference On Computer Communications. IEEE, 2019. and its repo [https://github.com/WSPTTH/FS-Net](https://github.com/WSPTTH/FS-Net).
